# Default values for kiem-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


kiem:
  image:
    repository: accuknox/kiem
    tag: "latest"

accuknoxJob:
  image:
    repository: accuknox/accuknox-job
    tag: "latest"

# To use existing secret, updated {imagePullSecrets.name} with your secret name.
imagePullSecrets:
  name: ""
  registry: ""
  username: ""
  password: ""


replicaCount: 1

accuknox:
  authToken: "NO-TOKEN-SET"
  URL: "cspm.demo.accuknox.com"
  tenantID: ""
  cronTab: "30 9 * * *"
  clusterName: ""
  label: ""
  secretName: ""
  saveToS3: "false"
  dataType: "KIEM"
  reportFile: "/data/report.json"
  gateway: ""
spire:
  secretName: "" 
  server: "" 
  port: "" 
  joinToken: ""
  namespace: ""
  configPath: ""